# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='qtd_likes',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade de Likes'),
        ),
    ]
