# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-28 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170627_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='file',
            field=models.ImageField(default='', upload_to='', verbose_name='Arquivo'),
        ),
    ]
