# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-03 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170627_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagem',
            name='qtd_followers',
            field=models.PositiveIntegerField(default=123, verbose_name='Quantidade de Followers'),
            preserve_default=False,
        ),
    ]
